import type { Metadata } from "next";
import "@/ui/globals.css";
import { ubntu } from "@/ui/font";
import Nav from "@/components/nav";
import Lines from "@/components/lines";
import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubntu.className}`}>
        <Lines />
        <Nav />
        {children}
      </body>
    </html>
  );
}
